#!/usr/bin/env python3
"""Build the paste-in prompts for platforms with no skills directory.

One file per module, each a complete self-contained copy of what the Claude
skill would load for it.

Each paste file is a complete, self-contained copy of what the Claude skill
would load for one flow:

    platform adapter  (instructions.md — the free-ChatGPT delta)
    SKILL.md          (verbatim, frontmatter stripped)
    references/*.md   (verbatim, the ones that flow cites)
    flows/<flow>.md   (verbatim)

Nothing is summarised or re-derived, so the portable route can't drift from
the skill the way a hand-maintained copy would. Editing SKILL.md, a flow, or
a reference and rebuilding is the whole maintenance story.

    python3 cofounder/portable/build.py          # write paste/
    python3 cofounder/portable/build.py --check  # verify, change nothing
"""

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SKILL = HERE.parent
PASTE = HERE / "paste"

# The GPT builder's Instructions box. Only the adapter has to fit it — the
# paste files are chat messages and have no such cap.
GPT_INSTRUCTION_LIMIT = 8000

# Rough characters per token, for the context-budget line in the output. The
# free-tier window is the binding constraint on these files, so the build
# reports it rather than leaving it to be discovered in a session.
CHARS_PER_TOKEN = 4

BANNER = """<!-- Generated by portable/build.py — do not edit.
     Edit ../SKILL.md, ../flows/{flow}.md, ../references/, or
     ../portable/instructions.md and rebuild. -->

*Paste this whole file into a new chat as your first message, then answer the
first question it asks. Bring your brief with you if you have one.*

"""


sys.path.insert(0, str(SKILL / "scripts"))
from flowmeta import FlowError, parse, split_frontmatter  # noqa: E402


def strip_frontmatter(text):
    """Drop a YAML header — it addresses the skill loader, not the model."""
    return split_frontmatter(text)[1]


def flows():
    return sorted(
        p.stem for p in (SKILL / "flows").glob("*.md") if not p.name.startswith("_")
    )


def cited_references(flow_text):
    """The references/ files this flow names, in first-mention order."""
    seen = []
    # Not preceded by a path segment: `marketing-workshop/references/x.md`
    # names another skill's file and is not ours to inline.
    for name in re.findall(r"(?<![\w/-])references/([a-z0-9-]+\.md)", flow_text):
        if name not in seen:
            seen.append(name)
    return seen


def build(flow):
    adapter = (HERE / "instructions.md").read_text().rstrip()
    skill = strip_frontmatter((SKILL / "SKILL.md").read_text()).rstrip()
    flow_text = strip_frontmatter((SKILL / "flows" / f"{flow}.md").read_text()).rstrip()

    parts = [BANNER.format(flow=flow) + adapter, skill]
    for name in cited_references(flow_text):
        path = SKILL / "references" / name
        if not path.exists():
            # main() reports this as a problem; skip it so the caller sees the
            # message rather than a traceback from the middle of a build.
            continue
        parts.append(f"# Reference — `references/{name}`\n\n{path.read_text().rstrip()}")
    parts.append(flow_text)
    return "\n\n---\n\n".join(parts) + "\n"


def main():
    check = "--check" in sys.argv
    problems = []

    adapter_size = len((HERE / "instructions.md").read_text())
    status = "ok" if adapter_size <= GPT_INSTRUCTION_LIMIT else "OVER LIMIT"
    print(f"instructions.md  {adapter_size:>6} chars  (GPT builder limit {GPT_INSTRUCTION_LIMIT}) {status}")
    if adapter_size > GPT_INSTRUCTION_LIMIT:
        problems.append(
            f"instructions.md is {adapter_size - GPT_INSTRUCTION_LIMIT} chars over the GPT builder limit"
        )

    expected = set()
    for flow in flows():
        flow_text = (SKILL / "flows" / f"{flow}.md").read_text()
        try:
            parse(SKILL / "flows" / f"{flow}.md")
        except FlowError as exc:
            problems.append(str(exc))
        for name in cited_references(flow_text):
            if not (SKILL / "references" / name).exists():
                problems.append(f"flows/{flow}.md cites references/{name}, which doesn't exist")

        out = PASTE / f"{flow}.md"
        expected.add(out.name)
        built = build(flow)
        if check:
            if not out.exists():
                problems.append(f"portable/paste/{flow}.md is missing — rerun build.py")
            elif out.read_text() != built:
                problems.append(f"portable/paste/{flow}.md is stale — rerun build.py")
        else:
            out.write_text(built)

        refs = cited_references(flow_text)
        note = f"+ {len(refs)} ref{'s' if len(refs) != 1 else ''}" if refs else ""
        print(f"  paste/{flow}.md{'':<{max(0, 14 - len(flow))}} {len(built):>6} chars  ~{len(built) // CHARS_PER_TOKEN // 100 * 100:>5} tokens  {note}")

    # A flow that's been renamed or removed leaves its paste file behind, which
    # would still look installable to anyone who has the link.
    for stray in sorted(PASTE.glob("*.md")):
        if stray.name not in expected:
            if check:
                problems.append(f"portable/paste/{stray.name} has no matching flow — rerun build.py")
            else:
                stray.unlink()
                print(f"  removed paste/{stray.name} (no matching flow)")

    for p in problems:
        print(f"  ! {p}")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
